[package]
name = "rae_text"
version = "0.1.0"
authors = ["Davide Corradi <davide.corradi.dev@gmail.com>"]
edition = "2018"

[dependencies]
freetype-rs = { version = "0.26" }
harfbuzz-sys = { version = "0.5" }
